# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e0fef3e0d1e9d770d4d06c4d98b4bb37020d5b1a5c8c56e534ecd47b61c09153d76b571b09a6eb61b1e26db479952d05dd67cb3c42b75356c17be912de51bfe

test:
  secret_key_base: 3c24dc4649eb93c897e6cf086e407274d8e8c5c445a3ba7464de80a98d12fc41e1ac517a824422484f9e9c60b31de7e223b5d89da082269b1970078e0d7f0abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
